LANGUAGES = [
	{ name: 'APL', mode: 'apl', slug: 'apl' },
	{ name: 'ASN.1', mode: 'asn.1', slug: 'asn1' },
	{ name: 'Asterisk', mode: 'asterisk', slug: 'asterisk' },
	{ name: 'Brainfuck', mode: 'brainfuck', slug: 'brainfuck' },
	{ name: 'C', mode: 'clike', slug: 'c' },
	{ name: 'C++', mode: 'clike', slug: 'cplusplus' },
	{ name: 'C#', mode: 'clike', slug: 'csharp' },
	{ name: 'Clojure', mode: 'clojure', slug: 'clojure' },
	{ name: 'CMake', mode: 'cmake', slug: 'cmake' },
	{ name: 'COBOL', mode: 'cobol', slug: 'cobol' },
	{ name: 'CoffeeScript', mode: 'coffeescript', slug: 'coffeescript' },
	{ name: 'Common Lisp', mode: 'commonlisp', slug: 'commonlisp' },
	{ name: 'Crystal', mode: 'crystal', slug: 'crystal' },
	{ name: 'CSS', mode: 'css', slug: 'css' },
	{ name: 'Cypher', mode: 'cypher', slug: 'cypher' },
	{ name: 'D', mode: 'd', slug: 'd' },
	{ name: 'Dart', mode: 'dart', slug: 'dart' },
	{ name: 'Diff', mode: 'diff', slug: 'diff' },
	{ name: 'Django', mode: 'django', slug: 'django' },
	{ name: 'Diff', mode: 'diff', slug: 'diff' },
	{ name: 'Dockerfile', mode: 'dockerfile', slug: 'dockerfile' },
	{ name: 'DTD', mode: 'dtd', slug: 'dtd' },
	{ name: 'Dylan', mode: 'dylan', slug: 'dylan' },
	{ name: 'EBNF', mode: 'ebnf', slug: 'ebnf' },
	{ name: 'ECL', mode: 'ecl', slug: 'ecl' },
	{ name: 'Eiffell', mode: 'eiffell', slug: 'eiffell' },
	{ name: 'Elm', mode: 'elm', slug: 'elm' },
	{ name: 'Erlang', mode: 'erlang', slug: 'erlang' },
	{ name: 'Factor', mode: 'factor', slug: 'factor' },
	{ name: 'FCL', mode: 'fcl', slug: 'fcl' },
	{ name: 'Forth', mode: 'forth', slug: 'forth' },
	{ name: 'Fortran', mode: 'fortran', slug: 'fortran' },
	{ name: 'Gas', mode: 'gas', slug: 'gas' },
	{ name: 'Gherkin', mode: 'gherkin', slug: 'gherkin' },
	{ name: 'Go', mode: 'go', slug: 'go' },
	{ name: 'Groovy', mode: 'groovy', slug: 'groovy' },
	{ name: 'HAML', mode: 'haml', slug: 'haml' },
	{ name: 'Handlebars', mode: 'handlebars', slug: 'handlebars' },
	{ name: 'Haskell', mode: 'haskell', slug: 'haskell' },
	{ name: 'Haxe', mode: 'haxe', slug: 'haxe' },
	{ name: 'HTML', mode: 'xml', slug: 'html' },
	{ name: 'HTML embedded', mode: 'htmlembedded', slug: 'htmlembedded' },
	{ name: 'HTML mixed mode', mode: 'htmlmixed', slug: 'htmlmixed' },
	{ name: 'HTTP', mode: 'http', slug: 'http' },
	{ name: 'IDL', mode: 'idl', slug: 'idl' },
	{ name: 'Java', mode: 'clike', slug: 'java' },
	{ name: 'JavaScript', mode: 'javascript', slug: 'javascript' },
	{ name: 'Julia', mode: 'julia', slug: 'julia' },
	{ name: 'Kotlin', mode: 'clike', slug: 'kotlin' },
	{ name: 'LaTeX', mode: 'stex', slug: 'latex' },
	{ name: 'LESS', mode: 'css', slug: 'less' },
	{ name: 'LiveScript', mode: 'livescript', slug: 'livescript' },
	{ name: 'Lua', mode: 'lua', slug: 'lua' },
	{ name: 'Markdown', mode: 'markdown', slug: 'markdown' },
	{ name: 'Mathematica', mode: 'mathematica', slug: 'mathematica' },
	{ name: 'mbox', mode: 'mbox', slug: 'mbox' },
	{ name: 'mIRC', mode: 'mirc', slug: 'mirc' },
	{ name: 'Modelica', mode: 'modelica', slug: 'modelica' },
	{ name: 'MscGen', mode: 'mscgen', slug: 'mscgen' },
	{ name: 'MUMPS', mode: 'mumps', slug: 'mumps' },
	{ name: 'Nginx', mode: 'nginx', slug: 'nginx' },
	{ name: 'NSIS', mode: 'nsis', slug: 'nsis' },
	{ name: 'N-Triples', mode: 'ntriples', slug: 'ntriples' },
	{ name: 'N-Quads', mode: 'ntriples', slug: 'nquads' },
	{ name: 'Objective C', mode: 'clike', slug: 'objectivec' },
	{ name: 'Octave', mode: 'octave', slug: 'octave' },
	{ name: 'Oz', mode: 'oz', slug: 'oz' },
	{ name: 'Pascal', mode: 'pascal', slug: 'pascal' },
	{ name: 'PEG.js', mode: 'pegjs', slug: 'pegjs' },
	{ name: 'Perl', mode: 'perl', slug: 'perl' },
	{ name: 'PHP', mode: 'php', slug: 'php' },
	{ name: 'Pig Latin', mode: 'pig', slug: 'pig' },
	{ name: 'PowerShell', mode: 'powershell', slug: 'powershell' },
	{ name: 'Properties Files', mode: 'properties', slug: 'properties' },
	{ name: 'ProtoBuf', mode: 'protobuf', slug: 'protobuf' },
	{ name: 'Pug', mode: 'pug', slug: 'pug' },
	{ name: 'Puppet', mode: 'puppet', slug: 'puppet' },
	{ name: 'Python', mode: 'python', slug: 'python' }, 
	{ name: 'Q', mode: 'q', slug: 'q' },
	{ name: 'R', mode: 'r', slug: 'r' },
	{ name: 'RPM', mode: 'rpm', slug: 'rpm' },
	{ name: 'React', mode: 'jsx', slug: 'jsx' },
	{ name: 'reStructuredText', mode: 'rst', slug: 'rst' },
	{ name: 'Ruby', mode: 'ruby', slug: 'ruby' },
	{ name: 'Ruby - ERB', mode: 'htmlembedded', slug: 'rubyerb' },
	{ name: 'Rust', mode: 'rust', slug: 'rust' },
	{ name: 'SAS', mode: 'sas', slug: 'sas' },
	{ name: 'SASS', mode: 'sass', slug: 'sass' },
	{ name: 'Scheme', mode: 'scheme', slug: 'scheme' },
	{ name: 'SCSS', mode: 'scss', slug: 'scss' },
	{ name: 'Shell', mode: 'shell', slug: 'shell' },
	{ name: 'Sieve', mode: 'sieve', slug: 'sieve' },
	{ name: 'Slim', mode: 'slim', slug: 'slim' },
	{ name: 'Smalltalk', mode: 'smalltalk', slug: 'smalltalk' },
	{ name: 'Smarty', mode: 'smarty', slug: 'smarty' },
	{ name: 'Solr', mode: 'solr', slug: 'solr' },
	{ name: 'Soy', mode: 'soy', slug: 'soy' },
	{ name: 'SPARQL', mode: 'sparql', slug: 'sparql' },
	{ name: 'SQL', mode: 'sql', slug: 'sql' },
	{ name: 'sTeX', mode: 'stex', slug: 'stex' },
	{ name: 'Swift', mode: 'swift', slug: 'swift' },
	{ name: 'Tcl', mode: 'tcl', slug: 'tcl' },
	{ name: 'Textile', mode: 'textile', slug: 'textile' },
	{ name: 'Tiddlywiki', mode: 'tiddlywiki', slug: 'tiddlywiki' },
	{ name: 'Tiki Wiki', mode: 'tiki', slug: 'tiki' },
	{ name: 'TOML', mode: 'toml', slug: 'toml' },
	{ name: 'Tornado', mode: 'tornado', slug: 'tornado' },
	{ name: 'troff', mode: 'troff', slug: 'troff' },
	{ name: 'TTCN', mode: 'ttcn', slug: 'ttcn' },
	{ name: 'TTCN Configuration', mode: 'ttcn-cfg', slug: 'ttcn-cfg' },
	{ name: 'Turtle', mode: 'turtle', slug: 'turtle' },
	{ name: 'Twig', mode: 'twig', slug: 'twig' },
	{ name: 'VB.NET', mode: 'vb', slug: 'vb' },
	{ name: 'VBScript', mode: 'vbscript', slug: 'vbscript' },
	{ name: 'Velocity', mode: 'velocity', slug: 'velocity' },
	{ name: 'Verilog', mode: 'verilog', slug: 'verilog' },
	{ name: 'VHDL', mode: 'vhdl', slug: 'vhdl' },
	{ name: 'Vue', mode: 'vue', slug: 'vue' },
	{ name: 'Web IDL', mode: 'webidl', slug: 'webidl' },
	{ name: 'XML', mode: 'xml', slug: 'xml' },
	{ name: 'XQuery', mode: 'xquery', slug: 'xquery' },
	{ name: 'Yacas', mode: 'yacas', slug: 'yacas' },
	{ name: 'YAML', mode: 'yaml', slug: 'yaml' },
	{ name: 'YAML Frontmatter', mode: 'yaml-frontmatter', slug: 'yaml-frontmatter' },
	{ name: 'Z80', mode: 'z80', slug: 'z80' }
].freeze