THEMES = [
  { slug: 'one-dark', name: 'One Dark', custom: true },
  { slug: '3024-day', name: '3024 Day', custom: false },
  { slug: '3024-night', name: '3024 Night', custom: false },
  { slug: 'abcdef', name: 'ABCDEF', custom: false },
  { slug: 'ambiance', name: 'Ambiance', custom: false },
  { slug: 'ayu-dark', name: 'Ayu Dark', custom: false },
  { slug: 'ayu-mirage', name: 'Ayu Mirage', custom: false },
  { slug: 'base16-dark', name: 'Base16 Dark', custom: false },
  { slug: 'base16-light', name: 'Base16 Light', custom: false },
  { slug: 'bespin', name: 'Bespin', custom: false },
  { slug: 'blackboard', name: 'Blackboard', custom: false },
  { slug: 'cobalt', name: 'Cobalt', custom: false },
  { slug: 'colorforth', name: 'Colorforth', custom: false },
  { slug: 'darcula', name: 'Darcula', custom: false },
  { slug: 'dracula', name: 'Dracula', custom: false },
  { slug: 'duotone-dark', name: 'Duotone Dark', custom: false },
  { slug: 'duotone-light', name: 'Duotone Light', custom: false },
  { slug: 'eclipse', name: 'Eclipse', custom: false },
  { slug: 'elegant', name: 'Elegant', custom: false },
  { slug: 'erlang-dark', name: 'Erlang Dark', custom: false },
  { slug: 'gruvbox-dark', name: 'Gruvbox Dark', custom: false },
  { slug: 'hopscotch', name: 'Hopscotch', custom: false },
  { slug: 'icecoder', name: 'Icecoder', custom: false },
  { slug: 'idea', name: 'Idea', custom: false },
  { slug: 'isotope', name: 'Isotope', custom: false },
  { slug: 'lesser-dark', name: 'Lesser Dark', custom: false },
  { slug: 'liquibyte', name: 'Liquibyte', custom: false },
  { slug: 'lucario', name: 'Lucario', custom: false },
  { slug: 'material', name: 'Material', custom: false },
  { slug: 'material-darker', name: 'Material Darker', custom: false },
  { slug: 'material-palenight', name: 'Material Palenight', custom: false },
  { slug: 'material-ocean', name: 'Material Ocean', custom: false },
  { slug: 'mbo', name: 'MBO', custom: false },
  { slug: 'mdn-like', name: 'MDN Like', custom: false },
  { slug: 'midnight', name: 'Midnight', custom: false },
  { slug: 'monokai', name: 'Monokai', custom: false },
  { slug: 'moxer', name: 'Moxer', custom: false },
  { slug: 'neat', name: 'Neat', custom: false },
  { slug: 'neo', name: 'Neo', custom: false },
  { slug: 'night', name: 'Night', custom: false },
  { slug: 'nord', name: 'Nord', custom: false },
  { slug: 'oceanic-next', name: 'Oceanic Next', custom: false },
  { slug: 'panda-syntax', name: 'Panda Syntax', custom: false },
  { slug: 'paraiso-dark', name: 'Paraiso Dark', custom: false },
  { slug: 'paraiso-light', name: 'Paraiso Light', custom: false },
  { slug: 'pastel-on-dark', name: 'Pastel on Dark', custom: false },
  { slug: 'railscasts', name: 'Railscasts', custom: false },
  { slug: 'rubyblue', name: 'Rubyblue', custom: false },
  { slug: 'seti', name: 'Seti', custom: false },
  { slug: 'shadowfox', name: 'Shadowfox', custom: false },
  { slug: 'solarized dark', name: 'Solarized Dark', custom: false },
  { slug: 'solarized light', name: 'Solarized Light', custom: false },
  { slug: 'the-matrix', name: 'The Matrix', custom: false },
  { slug: 'tomorrow-night-bright', name: 'Tomorrow Night Bright', custom: false },
  { slug: 'tomorrow-night-eighties', name: 'Tomorrow Night Eighties', custom: false },
  { slug: 'ttcn', name: 'TTCN', custom: false },
  { slug: 'twilight', name: 'Twilight', custom: false },
  { slug: 'vibrant-ink', name: 'Vibrant Ink', custom: false },
  { slug: 'xq-dark', name: 'XQ Dark', custom: false },
  { slug: 'xq-light', name: 'XQ Light', custom: false },
  { slug: 'yeti', name: 'Yeti', custom: false },
  { slug: 'yonce', name: 'Yonce', custom: false },
  { slug: 'zenburn', name: 'Zenburn', custom: false },
].freeze